[0.014s] Invoking command in '/home/nir/Desktop/rs485/build/rs485': CMAKE_PREFIX_PATH=/opt/ros/foxy:${CMAKE_PREFIX_PATH} CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake /home/nir/Desktop/rs485 -DCMAKE_INSTALL_PREFIX=/home/nir/Desktop/rs485/install/rs485
[0.023s] -- Found ament_cmake: 0.9.11 (/opt/ros/foxy/share/ament_cmake/cmake)
[0.046s] -- Using PYTHON_EXECUTABLE: /home/nir/anaconda3/bin/python3
[0.181s] -- Found rosidl_default_generators: 1.0.1 (/opt/ros/foxy/share/rosidl_default_generators/cmake)
[0.183s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.187s] -- Found rosidl_adapter: 1.3.0 (/opt/ros/foxy/share/rosidl_adapter/cmake)
[0.250s] -- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")  
[0.270s] -- Found FastRTPS: /opt/ros/foxy/include  
[0.320s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[0.353s] -- Found PythonInterp: /home/nir/anaconda3/bin/python3 (found version "3.9.13") 
[0.388s] CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
[0.388s]   execute_process(/home/nir/anaconda3/bin/python3 -m rosidl_adapter
[0.388s]   --package-name rs485 --arguments-file
[0.388s]   /home/nir/Desktop/rs485/build/rs485/rosidl_adapter__arguments__rs485.json
[0.388s]   --output-dir /home/nir/Desktop/rs485/build/rs485/rosidl_adapter/rs485
[0.388s]   --output-file
[0.388s]   /home/nir/Desktop/rs485/build/rs485/rosidl_adapter/rs485.idls) returned
[0.388s]   error code 1:
[0.388s] 
[0.388s]   Error processing 'float current' of 'rs485/GripperStatus': ''float' is an
[0.388s]   invalid message name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$''
[0.388s] 
[0.388s]   Traceback (most recent call last):
[0.388s] 
[0.388s]     File "/home/nir/anaconda3/lib/python3.9/runpy.py", line 197, in _run_module_as_main
[0.388s]       return _run_code(code, main_globals, None,
[0.388s]     File "/home/nir/anaconda3/lib/python3.9/runpy.py", line 87, in _run_code
[0.389s]       exec(code, run_globals)
[0.389s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[0.389s]       sys.exit(main())
[0.389s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[0.389s]       abs_idl_file = convert_to_idl(
[0.389s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[0.389s]       return convert_msg_to_idl(
[0.389s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[0.389s]       msg = parse_message_string(package_name, input_file.stem, content)
[0.389s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 516, in parse_message_string
[0.389s]       Type(type_string, context_package_name=pkg_name),
[0.389s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 276, in __init__
[0.389s]       super(Type, self).__init__(
[0.389s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 204, in __init__
[0.389s]       raise InvalidResourceName(
[0.389s] 
[0.389s]   rosidl_adapter.parser.InvalidResourceName: 'float' is an invalid message
[0.389s]   name.  It should have the pattern '^[A-Z][A-Za-z0-9]*$'
[0.389s] 
[0.389s] Call Stack (most recent call first):
[0.389s]   /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[0.389s]   CMakeLists.txt:24 (rosidl_generate_interfaces)
[0.389s] 
[0.389s] 
[0.389s] -- Configuring incomplete, errors occurred!
[0.389s] See also "/home/nir/Desktop/rs485/build/rs485/CMakeFiles/CMakeOutput.log".
[0.393s] Invoked command in '/home/nir/Desktop/rs485/build/rs485' returned '1': CMAKE_PREFIX_PATH=/opt/ros/foxy:${CMAKE_PREFIX_PATH} CONDA_PROMPT_MODIFIER=(base) /usr/bin/cmake /home/nir/Desktop/rs485 -DCMAKE_INSTALL_PREFIX=/home/nir/Desktop/rs485/install/rs485
